services:
  # Backend API service
  - type: web
    name: restomart-task-manager-api
    env: node
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: restomart-db
          property: connectionString

  # Frontend static site
  - type: web
    name: restomart-task-manager-frontend
    env: static
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: restomart-db
    plan: free
    databaseName: taskmanager
    ipAllowList: []